# Justfile for synth-engine table generation
# Usage: just <recipe>

# Default recipe - show available commands
default:
    @just --list

compile:
    @echo "Compiling"
    @mdbook build

write:
    @echo "Compiling and watching for changes..."
    @mdbook serve

spell-check:
    @echo "Checking for spelling errors"
    @cspell **/*.md

spell-watch:
    @echo "Watching for spelling errors"
    @find . -name '*.md' | entr -c cspell **/*.md

spell-add-unknown:
    @echo "Adding unknown words to dictionary"
    @echo "# Unknown words" >> project-words.txt
    @cspell --words-only --unique **/*.md | sort --ignore-case >> project-words.txt
