//! Generated octave filter coefficients
//! DO NOT EDIT - Generated by generate_equalizer_coefficients.rs

use cmsis_interface::Q15;

/// Post-shift value for biquad cascade filter
/// Coefficients are pre-shifted right by 1 bits, so postShift = 1
pub const EQUALIZER_POST_SHIFT: i8 = 1;

/// Octave filter coefficients for 6 bands
/// Band 0: Low-pass filter
/// Bands 1-4: Bandpass filters (1st order Butterworth)
/// Band 5: High-pass filter
/// Coefficient format per stage: [b0, 0, b1, b2, a1, a2] (CMSIS format with zero padding)
/// Coefficients are pre-shifted right by 1 bits to prevent overflow
pub static EQUALIZER_COEFFS: [[Q15; 6]; 6] = [
    // Band 0 (Low-pass at 250.0 Hz)
    [
        Q15::from_bits(264),
        Q15::from_bits(0),
        Q15::from_bits(264),
        Q15::from_bits(0),
        Q15::from_bits(15856),
        Q15::from_bits(0),
    ],
    // Band 1 (Bandpass 353.6-707.1 Hz)
    [
        Q15::from_bits(370),
        Q15::from_bits(0),
        Q15::from_bits(0),
        Q15::from_bits(-370),
        Q15::from_bits(31959),
        Q15::from_bits(-15643),
    ],
    // Band 2 (Bandpass 707.1-1414.2 Hz)
    [
        Q15::from_bits(726),
        Q15::from_bits(0),
        Q15::from_bits(0),
        Q15::from_bits(-726),
        Q15::from_bits(31049),
        Q15::from_bits(-14934),
    ],
    // Band 3 (Bandpass 1414.2-2828.4 Hz)
    [
        Q15::from_bits(1391),
        Q15::from_bits(0),
        Q15::from_bits(0),
        Q15::from_bits(-1391),
        Q15::from_bits(28960),
        Q15::from_bits(-13600),
    ],
    // Band 4 (Bandpass 2828.4-5656.9 Hz)
    [
        Q15::from_bits(2584),
        Q15::from_bits(0),
        Q15::from_bits(0),
        Q15::from_bits(-2584),
        Q15::from_bits(23860),
        Q15::from_bits(-11215),
    ],
    // Band 5 (High-pass at 8000.0 Hz)
    [
        Q15::from_bits(10387),
        Q15::from_bits(0),
        Q15::from_bits(-10387),
        Q15::from_bits(0),
        Q15::from_bits(4389),
        Q15::from_bits(0),
    ],
];
