[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[features]
default = ["stm32h723zg", "midi-config", "peripheral-config", "midi-usb", "audio-usb", "equalizer"]
config = []
midi-config = ["config", "midi/midi-config"]
peripheral-config = ["config"]
stm32h723zg = ["embassy-stm32/stm32h723zg", "cmsis-native/stm32h723zg"]
stm32f401rc = ["embassy-stm32/stm32f401rc", "cmsis-native/stm32f401rc"]
usb = ["dep:embassy-usb"]
midi-din = []
midi-usb = ["usb"]
audio-usb = ["usb"]
equalizer = ["synth_engine/equalizer"]

[profile.release]
debug = 2
lto = "fat"
opt-level = "z"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "defmt", "executor-thread", "executor-interrupt"] }
embassy-stm32 = { version = "0.4.0", features = ["defmt", "memory-x", "time", "time-driver-any", "exti"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb = { version = "0.5.1", features = ["defmt"], optional = true }
fixed = "1.29.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
amity = { version = "0.6.3", default-features = false, features = ["triple"] }
static_cell = "2.1.1"
bytemuck = "1.20.0"
midi = { path = "../midi", default-features = false }
synth_engine = { path = "../synth-engine", default-features = false }
cmsis-native = { path = "../cmsis-native", default-features = false }
config = { path = "../config" }

[build-dependencies]
toml = "0.8"
