[chip]
model = "stm32h723zg"
# model = "stm32f401rc"

[connections]
midi = "usb"
# midi = "din"
# midi = "none"

audio = "usb"
# audio = "none"

[features]
octave_filter = true
configurable = true

[parameters]
polyphony = 16
# Increase it to make the encoders more responsive.
# Make it negative to invert them.
encoder_multiplier = 4
# How often to poll peripherals for changes in milliseconds
config_poll_millis = 5
# How often to update the config in miliseconds
config_update_millis = 100

[initial_config]
# All values in this section are in the range 0 to 255
attack = 40
sustain = 127
decay_release = 200
# Wavetable depends on the value mod 4
#   0 => Sine
#   1 => Saw
#   2 => Square
#   3 => Triangle
oscilator_type = 1
# Equalizer
f250hz = 200
f500hz = 200
f1000hz = 200
f2000hz = 200
f4000hz = 200
f8000hz = 200
