[package]
name = "midi"
version = "0.1.0"
edition = "2024"

[features]
default = ["midi-config"]
midi-config = []

[dependencies]
embassy-sync = "0.7.2"
midly = { version = "0.5.3", default-features = false }
defmt = "1.0.1"
config = { path = "../config" }

[dev-dependencies]
midly = { version = "0.5.3" }
pretty_assertions = "1.4.1"
