# Justfile for synth-engine table generation
# Usage: just <recipe>

# Default recipe - show available commands
default:
    @just --list

generate-images:
    @echo "Generating images"
    @python ./scripts/adsr_diagrams.py
    @python ./scripts/filter_bank_diagrams.py
    @python ./scripts/performance_diagrams.py

write:
    @echo "Compiling and watching for changes..."
    @typst watch main.typ
    @open main.pdf

spell-check:
    @echo "Checking for spelling errors"
    @cspell **/*.typ **/*.bib

spell-watch:
    @echo "Watching for spelling errors"
    @find . -name '*.typ' -o -name '*.bib' | entr -c cspell **/*.typ **/*.bib

spell-add-unknown:
    @echo "Adding unknown words to dictionary"
    @echo "# Unknown words" >> project-words.txt
    @cspell --words-only --unique **/*.typ **/*.bib | sort --ignore-case >> project-words.txt

compile:
    @echo "Compiling"
    @typst compile main.typ
